// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:
// Input: s = "", t = "y"
// Output: "y"

var findTheDifference = function (s, t) {
  for (let i = 0; i < t.length; i++) {
    const str1 = s.split("").sort();
    const str2 = t.split("").sort();
    if (str2[i] != str1[i]) {
      return str2[i];
    }
  }
};
